### ISSUE TITLE
The Schematics simply do not place

### ISSUE THREAD

**Issue by GyroHub** [cakeGit/Pattern-Schematics#1]
The title says it all, this bug not only applies to pattern schematics but also normal schematics so the entire schematic system is bricked

![image](https://github.com/user-attachments/assets/0268f57e-db07-49cc-b0a4-43695d97001f)
![image](https://github.com/user-attachments/assets/6057b833-de86-4321-b02f-9970488321a4)

here are all the mods

version 1.20.1

this is my 2nd ever github bug report and the first one was a while back
hope this helps

**Comment by cakeGit** [comment]
do you have a latest .log?

**Comment by cakeGit** [comment]
nevermind im trying it on my end and having the same issue, its only in production for some reason? this might take me a bit x_x

**Comment by cakeGit** [comment]
Found the error, fixed in latest version! Thank you so much for the report, my fault for the oversight,
